import meal from './../assets/meal.mp4'
import random from './../assets/Assets-1.jpeg'
import second from './../assets/Assets-1.jpeg'
import third from './../assets/Assets-3.jpeg'
import fourth from './../assets/Assets-4.jpeg'
import fifth from './../assets/Assets-5.jpeg'
import sixth from './../assets/Assets-6.jpeg'
import seventh from './../assets/Assets-7.jpeg'
import eighth from './../assets/Assets-8.jpeg'
import ninth from './../assets/Assets-9.jpeg'
import tenth from './../assets/Assets-10.jpeg'
import eleventh from './../assets/Assets-11.jpeg'
import twelveth from './../assets/Assets-12.jpeg'
import thirteenth from './../assets/Assets-13.jpeg'
import fourteen from './../assets/Assets-14.jpeg'
import fifteen from './../assets/Assets-15.jpeg'
import sixteen from './../assets/Assets-16.jpeg'
import seventeen from './../assets/Assets-17.jpeg'
import eighteen from './../assets/Assets-18.jpeg'
import nineteen from './../assets/Assets-19.jpeg'
import twenty from './../assets/Assets-20.jpeg'

export { meal, random, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelveth, thirteenth, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty }